#%RAML 1.0 Trait
responses:
	202: 
		body:
			application/json:
				example: |
					{"message":"Successful database modication"}
	400:
		body:
			application/json:
				example: |
					{"message":"Database modification unsuccessful"}